#!/bin/bash
# http://beerpla.net/2010/06/10/how-to-display-just-the-http-response-code-in-cli-curl/
if (( $# -ne 1 )); then
    # TODO: print usage
    exit 1
fi

curl -sL -w "%{http_code} %{url_effective} \\n" $@ -o /dev/null

