#!/usr/bin/env python
# Accepts an epoch and converts it into a human readable time
# date -d @1478587042

import time
import sys 

if __name__ == '__main__':
    myepoch = 1478587042
    if len(sys.argv) < 2:
        print('Usage:' + sys.argv[0] + ' <time_in_epoch_secs>')
        print(' Ex:' + sys.argv[0] + ' 1478587042')
        sys.exit(1)
    myepoch = int(sys.argv[1])
    print (time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(myepoch)))
