#!/bin/bash
# to print only leaf dirs
# for i in `./leafdirs`; do basename $i; done

# Find all directories
find . -type d | while read -r dir; do
    # Check if the directory contains any subdirectories
    subdirs=$(find "$dir" -mindepth 1 -type d | wc -l)

    # If no subdirectories, print the directory (it's a leaf directory)
    if [[ $subdirs -eq 0 ]]; then
        echo "$dir"
    fi
done
