#!/bin/bash
ip route get 1 | awk '{print $NF;exit}'
#very long cmd to do the same thing - what I could come up with without looking at the net
#ip a | grep "inet " | grep -v docker | grep global| grep -v virbr | awk '{print $2}' | awk -F '/' '{print $1}'
#ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'
#ifconfig  | grep -E 'inet.[0-9]' | grep -v '127.\|169.' | awk '{ print $2}'
