#!/usr/bin/env python

# script to send email 
# accepts subject, body and attachment as args
# Usage:" + sys.argv[0] + ' <subject> <file_body.txt> [file_attachment.extn]

from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
import smtplib
import sys
import datetime

def date_str():
    pstr = str(datetime.datetime.now().strftime('%Y-%m-%d-%H:%M:%S'))
    return str(pstr)

################################################################################
#####################   CONFIGURATION PARMARETERS ##############################   
config_from = 'sender@gmail.com'
config_from_password =  "XXXXX"
config_recipients = ['rohit@gmail.com', 'receiver@gmail.com']
################################################################################

opt_config_reply_to = config_from


if __name__ == '__main__':
    argc = len(sys.argv)
    #print('argc:' + str(argc))
    if argc < 3 or argc > 4:
        print("Usage:" + sys.argv[0] + ' <subject> <file_body.txt> [file_attachment.extn]')
        sys.exit(1)
    # get the positional args
    arg_subject = str(sys.argv[1])
    arg_body = str(sys.argv[2])
    if argc == 4:
        # third arg is filename of the attachment      
        arg_attachment = str(sys.argv[3])
    else:
        arg_attachment = None
    #print('arg_attachment:' + str(arg_attachment))    

    recipients = config_recipients
    emaillist = [elem.strip().split(',') for elem in recipients]
    msg = MIMEMultipart()
    msg['Subject'] = arg_subject
    msg['From'] = config_from
    msg['Reply-to'] = opt_config_reply_to
    msg.preamble = 'Multipart message.\n'

    # read file as string for the body
    with open(arg_body) as f:
        body_str = f.read()

    #part = MIMEText("Hi, please find the attached file")
    part = MIMEText(body_str)
    msg.attach(part)

    if arg_attachment is not None:
        part = MIMEApplication(open(arg_attachment,"rb").read())
        part.add_header('Content-Disposition', 'attachment', filename=arg_attachment)
        msg.attach(part)

    try:
        server = smtplib.SMTP("smtp.gmail.com:587")
        server.ehlo()
        server.starttls()
        server.login(config_from, config_from_password)
        server.sendmail(msg['From'], emaillist , msg.as_string())
    except Exception, exc:
        sys.exit( "mail failed; %s" % str(exc) ) # give a error message

    print 'Mail sent at ' + date_str()
