#!/bin/bash
# zeroes out all files on a dir 
# whose contents can then never be retrieved
# -- Use with Caution
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <dir> "
    echo "ex. $0 ."
	exit 1
fi
PASSED=$1

if [[ ! -d $PASSED ]]; then
    #Only works on a dir
	echo [$1] is not a dir
	exit 1
fi

read -p "This will zero out all files in $PASEED Are you sure [y/n] ?" -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

OIFS="$IFS"
IFS=$'\n'
for i in `find $PASSED -type f -name "*"` 
do
   # $i iterates through each filename in the dir
   echo truncating file [$i]
   # the next command truncates the file
   echo > $i 
done
IFS="$OIFS"
